# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common.monaifl_pb2 as monaifl__pb2


class MonaiFLServiceStub(object):
    """FL service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParamTransfer = channel.unary_unary(
                '/protobufs.MonaiFLService/ParamTransfer',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.ModelTransfer = channel.unary_unary(
                '/protobufs.MonaiFLService/ModelTransfer',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.ReportTransfer = channel.unary_unary(
                '/protobufs.MonaiFLService/ReportTransfer',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.MessageTransfer = channel.unary_unary(
                '/protobufs.MonaiFLService/MessageTransfer',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.NodeStatus = channel.unary_unary(
                '/protobufs.MonaiFLService/NodeStatus',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.TrainedModel = channel.unary_unary(
                '/protobufs.MonaiFLService/TrainedModel',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )
        self.StopMessage = channel.unary_unary(
                '/protobufs.MonaiFLService/StopMessage',
                request_serializer=monaifl__pb2.ParamsRequest.SerializeToString,
                response_deserializer=monaifl__pb2.ParamsResponse.FromString,
                )


class MonaiFLServiceServicer(object):
    """FL service 
    """

    def ParamTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MessageTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainedModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonaiFLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParamTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ParamTransfer,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'ModelTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelTransfer,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'ReportTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTransfer,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'MessageTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.MessageTransfer,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'NodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeStatus,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'TrainedModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainedModel,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
            'StopMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMessage,
                    request_deserializer=monaifl__pb2.ParamsRequest.FromString,
                    response_serializer=monaifl__pb2.ParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobufs.MonaiFLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonaiFLService(object):
    """FL service 
    """

    @staticmethod
    def ParamTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/ParamTransfer',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/ModelTransfer',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/ReportTransfer',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MessageTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/MessageTransfer',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/NodeStatus',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainedModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/TrainedModel',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobufs.MonaiFLService/StopMessage',
            monaifl__pb2.ParamsRequest.SerializeToString,
            monaifl__pb2.ParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
