# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monaifl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monaifl.proto',
  package='protobufs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonaifl.proto\x12\tprotobufs\"%\n\rParamsRequest\x12\x14\n\x0cpara_request\x18\x01 \x01(\x0c\"\'\n\x0eParamsResponse\x12\x15\n\rpara_response\x18\x02 \x01(\x0c\x32\xf7\x03\n\x0eMonaiFLService\x12\x44\n\rParamTransfer\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x44\n\rModelTransfer\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x45\n\x0eReportTransfer\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x46\n\x0fMessageTransfer\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x41\n\nNodeStatus\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x43\n\x0cTrainedModel\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponse\x12\x42\n\x0bStopMessage\x12\x18.protobufs.ParamsRequest\x1a\x19.protobufs.ParamsResponseb\x06proto3'
)




_PARAMSREQUEST = _descriptor.Descriptor(
  name='ParamsRequest',
  full_name='protobufs.ParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='para_request', full_name='protobufs.ParamsRequest.para_request', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=65,
)


_PARAMSRESPONSE = _descriptor.Descriptor(
  name='ParamsResponse',
  full_name='protobufs.ParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='para_response', full_name='protobufs.ParamsResponse.para_response', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['ParamsRequest'] = _PARAMSREQUEST
DESCRIPTOR.message_types_by_name['ParamsResponse'] = _PARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParamsRequest = _reflection.GeneratedProtocolMessageType('ParamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARAMSREQUEST,
  '__module__' : 'monaifl_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.ParamsRequest)
  })
_sym_db.RegisterMessage(ParamsRequest)

ParamsResponse = _reflection.GeneratedProtocolMessageType('ParamsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARAMSRESPONSE,
  '__module__' : 'monaifl_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.ParamsResponse)
  })
_sym_db.RegisterMessage(ParamsResponse)



_MONAIFLSERVICE = _descriptor.ServiceDescriptor(
  name='MonaiFLService',
  full_name='protobufs.MonaiFLService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=612,
  methods=[
  _descriptor.MethodDescriptor(
    name='ParamTransfer',
    full_name='protobufs.MonaiFLService.ParamTransfer',
    index=0,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ModelTransfer',
    full_name='protobufs.MonaiFLService.ModelTransfer',
    index=1,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReportTransfer',
    full_name='protobufs.MonaiFLService.ReportTransfer',
    index=2,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MessageTransfer',
    full_name='protobufs.MonaiFLService.MessageTransfer',
    index=3,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NodeStatus',
    full_name='protobufs.MonaiFLService.NodeStatus',
    index=4,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainedModel',
    full_name='protobufs.MonaiFLService.TrainedModel',
    index=5,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopMessage',
    full_name='protobufs.MonaiFLService.StopMessage',
    index=6,
    containing_service=None,
    input_type=_PARAMSREQUEST,
    output_type=_PARAMSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONAIFLSERVICE)

DESCRIPTOR.services_by_name['MonaiFLService'] = _MONAIFLSERVICE

# @@protoc_insertion_point(module_scope)
